# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 哈姆詤的箌悝糖
subtitle: ''
description: ''
keywords:
author: emokable
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.emokable.top/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
#<-这里插入abbrlink配置
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'pdfjs/**'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Emokable/Emokable.github.io.git
  branch: main

# minifier
all_minifier: true
html_minifier:
  enable: true
  ignore_error: true
  exclude:
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  #output:
  compress:
  exclude:
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

 # Extensions
 ## Plugins: http://hexo.io/plugins/
 #RSS订阅
feed: 
type: atom #RSS的类型(atom/rss2)
path: atom.xml #文件路径,默认是atom.xml/rss2.xml
limit: 20 #展示文章的数量,使用0或则false代表展示全部
hub: 
content:  #在RSS文件中是否包含内容 ,有3个值 true/false默认不填为false
content_limit: 140 #指定内容的长度作为摘要,仅仅在上面content设置为false和没有自定义的描述出现
content_limit_delim: " " #上面截取描述的分隔符,截取内容是以指定的这个分隔符作为截取结束的标志.在达到规定的内容长度之前最后出现的这个分隔符之前的内容,，防止从中间截断
order_by: -date
icon: #icon.png

sitemap:
   path: sitemap.xml 

steam:
  enable: true  # enable: 是否启用
  steamId: ' 76561199236571966' #steam 64位Id
  apiKey: '09186CED1A6311DE24DCDFB83CFF94EC' #steam api key
  steamInfos: # 多账号配置
    - id: '  76561199236571966' #steam 64位Id
      path:  # 为每个帐号游戏库单独配置页面路径，默认`steamgames/{steamId}/index.html`
      # 76561198802948600  76561199236571966
  freeGames: true  
  path:
  title: Steam游戏库  #该页面的标题
  quote: '目前这个插件还是有点问题'  #写在页面开头的一段话,支持html语法
  tab: recent  #all或recent, all: 所有游戏, recent: 最近游玩的游戏
  length: 5000  #要显示游戏的数量，游戏太多的话可以限制一下
  imgUrl: ''  #图片链接，在quote下面放一张图片，图片链接到Steam个人资料，可留空
  proxy: #如果无法访问steam社区的话请使用代理
    host:
    port:
  extra_options: #此配置会扩展到Hexo的page变量中
    key: value





